### ISSUE TITLE
Supply Depos do not follow Last In First Out like other Factorio storage entities

### ISSUE THREAD

**Issue by Lyko5** [Klonan/Transport_Drones#10]
# Background:
The vanilla Factorio chests and storage entities follow a pseudo LIFO (Last In First Out) method of storage for stacks.
This means if an inserter places and item in to a chest, it will fill the first matching stack from top-left to right, then next row, just like reading a book. When an inserter removes items it is reversed, from bottom-right to left, then up to the next row. In doing so, this respects taking items from the red areas before other items are inserted.

# Issue:
I have noticed the supply depots do not follow this same method. I have (almost) filled a supply depot manually (to empty my player inventory), and set the red block area. Then the drones are coming by and taking from the top-left leaving hundreds of items "stuck" in the supply depot making upstream machines work when they don't need to.

Image:
![Supply-Depot-Notes](https://user-images.githubusercontent.com/5974264/85210680-0ef4e300-b310-11ea-9ea9-52570624588d.png)

# Expected Result:
I would expect the supply depots to follow the same default LIFO method. Taking stacks from bottom-right to left, then up to leverage the red blocking area.

**Comment by Klonan** [comment]
Sorry, but I am just using some normal typical inventory API call to remove and insert items, to fix this would mean iterating stacks in Lua, which is expensive and bad for performance
