### ISSUE TITLE
Angel's used coolant bug

### ISSUE THREAD

**Issue by LovelySanta** [Klonan/Transport_Drones#16]
As reported in Arch666Angel/mods#380, the used coolant has a default temperature of 25°, however when it comes out of the machines that produce it, it has a temperature of 300°. This fluid requires to be cooled down to 25°C before being able to transport it. I would suggest adding a max_temperature of 25°, or give some margin like 35° at most for the input recipe. The output recipe correctly defaults to 25° then. I would not allow transporting the hot fluid at all.

**Comment by Klonan** [comment]
I think I fixed it
