### ISSUE TITLE
"mining" road tiles generates unlimited tiles from the patch in front of the depot...

### ISSUE THREAD

**Issue by slippycheeze** [Klonan/Transport_Drones#24]
Unlimited road tile generation, presumably unintended:
1. place a drone fuel depot.  (presumably anything with the tile, but this is how I found it.)
2. pick up a bit of road in your hand
3. right-click to mine the bit of road that comes automatically at the front of the depot
4. watch unlimited entities come in :)

**Comment by Klonan** [comment]
does it really though?

**Comment by Mejari** [comment]
Came here to report a similar issue.

```
base: 1.1.69
Mining_Drones: 1.1.10
Transport_Drones: 1.0.10
```

Steps to reproduce: 

1: Place a Mining depot
2: Place Fast Road over the automatically generated road exiting the Mining depot
3: Hold down right-mouse to disassemble road

Expected Results:

Either the Fast Road in the location of the automatically generated road is removed leaving no road exiting the Mining depot or the fast road is removed and replaced with normal road.

Actual Results:

Fast Roads will  continuously be picked up without removing the Fast Road placed over the automatically generated road, placing them in your inventory as usable items.


After seeing this existing report I checked and was able to reproduce the same behavior with Buffer, Request and Supply depots. Same behavior occurs if I disable the Mining Drones mod and test against Buffer, Request and Supply depots.

Doing the same steps with normal road acts as though it's continuously removing road but does not add the phantom road to your inventory.
