### ISSUE TITLE
Removing Supply Depot cause non recoverable Error when Space Scaffolding is not present underneath

### ISSUE THREAD

**Issue by Bollmeister** [Klonan/Transport_Drones#30]
Dear Maintainer,

we spotted a bug during gameplay.

Healing: None
Factorio with Version 1.1.46

**Relevant and used mods:**
- Krasstorio 2 (1.1.6)
- Space Exploration (0.50.90)
- Transport Drones (1.0.4)

**Steps to Reproduce:**

- Build Supply Depot
- Remove Scaffolding around depot and under supply depot
- Notice: Supply Depot graphics are gone by then, but Supply Depot can still be removed by player
- Remove Supply Depot
- Following exception is thrown (note: this log with caused by robots): 
```
The mod Transport Drones (1.0.4) caused a non-recoverable error.
Please report this error to the mod author.
Error while running event Transport_Drones::on_robot_mined_entity (ID 65)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
	[C]: in function '__newindex'
	__Transport_Drones__/script/depots/supply_depot.lua:134: in function 'on_removed'
	__Transport_Drones__/script/depot_common.lua:298: in function 'remove_depot'
	__Transport_Drones__/script/depot_common.lua:308: in function 'handler'
	__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>
```
- This error was caused by player as shown in video
<img width="444" alt="image" src="https://user-images.githubusercontent.com/7882790/141837547-535d1f3c-c8c3-4a53-8eda-3d076bc49e20.png">

Could you please have a look?

https://user-images.githubusercontent.com/7882790/141836087-0789104d-8bf8-42b5-a98b-2a0fd6633ea6.mov

**Comment by Klonan** [comment]
Can you provide a save game?

**Comment by Bollmeister** [comment]
> Can you provide a save game?

https://drive.google.com/file/d/1TfqqDTOuqNXDHF0_Qs53ufbVAEOc73gQ/view?usp=sharing

Here is also one factory that cannot be removed (for you to find the spot easier):
<img width="179" alt="image" src="https://user-images.githubusercontent.com/7882790/141981614-59a8afab-032a-40c4-94b4-d4f7c214e79c.png">

**Comment by Klonan** [comment]
should be fixed now

**Comment by Bollmeister** [comment]
Looks very good!

Thank you for fixing this issue

Regards from Berlin
Christian
