### ISSUE TITLE
QoL: "Take" button

### ISSUE THREAD

**Issue by socek** [Klonan/Transport_Drones#38]
On open "request depot" dialog, when you have already chosen the recipe (what to request), we can add drones. The problem is, that searching for drones in the inventory can be time consuming if we have increased inventory size.
 To solve this I propose 3 buttons underneath the drones icon:
 - take 1
 - take 5
 - take max
 Take means "take from the inventory".

**Comment by OldStarchy** [comment]
You can make a dedicated inventory slot for drones by middle clicking, then the drones will always be in the same location

**Comment by socek** [comment]
OMFG. I didn't know about this feature. Thanks a lot mate!
