### ISSUE TITLE
[SE] "mounting" drones from satellite view allows teleporting

### ISSUE THREAD

**Issue by OldStarchy** [Klonan/Transport_Drones#39]
1. Enter the satellite view from Space Exploration (default shortcut "N")
2. Mount a drone (default shortcut "Enter")
3. Leave satellite view ("N")
4. Player character is teleported to drone

I haven't tried doing this from a different surface (eg from space) as I'm worried it might crash or do something weird.

**Comment by Klonan** [comment]
It should work fine, theoretically the character is still riding the drone
