### ISSUE TITLE
non-recoverable error "TransportDrones::on_player_mined_entity"

### ISSUE THREAD

**Issue by lintaba** [Klonan/Transport_Drones#4]
https://github.com/Klonan/Transport_Drones/blob/2c512be244034fadc811e0a9654643c310e96d7d/script/depots/mining_depot.lua#L140

mined a mining depo, that crashed the server.

![image](https://user-images.githubusercontent.com/375078/79055126-c0a9d080-7c4a-11ea-85fd-4904e0ebf9c4.png)

**Comment by Klonan** [comment]
Yea, it shouldn't be possible, it is in a bad state, not sure why

**Comment by Klonan** [comment]
seems fixed in the latest releases
