### ISSUE TITLE
Issue/Enhancement: Depots do not translate properly to blueprints

### ISSUE THREAD

**Issue by arroo** [Klonan/Transport_Drones#42]
Supply Depot: A supply depot in a blueprint with some slots disabled does not get placed properly when placed from a blueprint
Request (Buffer?) Depot: an enhancement that would be the cherry on this mod would be if, when making a blueprint of a request depot, its count of drones is part of the blueprint and construction drones were able to place them, a la modules
Note: this would also apply for mining depots & drones. I can make an issue there too if desired.

**Comment by Klonan** [comment]
Didn't I just do this?
