### ISSUE TITLE
Roads autoplacing when placing Depots

### ISSUE THREAD

**Issue by bear989** [Klonan/Transport_Drones#44]
when you place a depot down there is road places into it witch doesnt delete when you pick up the depot giving you free road. should be easily fixed by costing road to make the depot or not auto connecting the road to the caution area in front.
https://clips.twitch.tv/SpunkyConfidentFlyLeeroyJenkins-fvt79qUP8EIKkQWl

**Comment by Klonan** [comment]
I don't worry about 1 piece of free road

**Comment by bear989** [comment]
but one piece of free road could be a complete road with enough placing and removing.
