### ISSUE TITLE
Drones don't pickup 0 degree fluids

### ISSUE THREAD

**Issue by marsh1832** [Klonan/Transport_Drones#45]
Fluid drone requests that used to work no longer do. The fluid trucks drive up to the fluid depot, act like they picked something up, but don't, and return. Nothing gets moved. I think this is related to the fluid temp. Most of my fluids in an Angel Bobs save are 0 degrees for some reason, after the recent updates. I made some drone requests for water and steam, which are non-zero temps, and the drones worked fine, so there seems to be an issue with drones picking up 0 degree fluids.

**Comment by Klonan** [comment]
Can you provide a save game with the issue?

**Comment by marsh1832** [comment]
https://drive.google.com/file/d/1yJWRHifF7G3Vo-tauB-d4NALzilw44rt/view?usp=share_link

Here's a save file. If you wish to load it you may have to disable science cost tweaker, the recent update broke some of it and it needed modification to load. The Marshtunes mod is just a local mod mainly to change the volume of certain machines to make it more youtube friendly

**Comment by Klonan** [comment]
This is a base game bug, the fluid in the depot somehow has the wrong temperature,
You can use this command to fixup the fluids:
```lua
/c   for k, entity in pairs (game.player.surface.find_entities_filtered{}) do   local fluidboxes = entity.fluidbox   for k = 1, #fluidboxes do     local box = fluidboxes[k]     if box then       fluidboxes[k] = box     end   end end```
