### ISSUE TITLE
virtual signal field length - too long

### ISSUE THREAD

**Issue by Leucetius** [Klonan/Transport_Drones#6]
Due to changing the internal prototype name in some cases the above named field gets too long.

> 235.151 Mods to disable:Failed to load mods: Error while loading virtual-signal prototype "fluid-depot-high-pressure-liquid-nutrient-pulp" (virtual-signal): Order field is too large. Max allowed size is: 200.

Modifications: Transport Drones

This is generated in the combination
Transport Drones 0.6.5
Compressed Fluids 0.1.17
I already opened an issue over at lovely_santa's (https://github.com/LovelySanta/FactorioMod-OtherSmallMods/issues/13) but he rejected because your mod is named. I already told him, that both your mods add to the field and in combination it gets to long...

Maybe changing +"fluid-depot-" to something shorter does the trick. Or rambling about that at Wube and the field gets larger...

**Comment by Klonan** [comment]
Nothing to do with me.

I set the order of my things to just the order of the fluids. Just because I make a recipe with a long name doesn't mean it is my issue.
