### ISSUE TITLE
Transport Drones and Bob's & Angel's mods

### ISSUE THREAD

**Issue by jameinel** [Klonan/Transport_Drones#7]
I wanted to check what you think the correct fix for this is.

I'm doing a heavily modded Bob's & Angel's run, and I thought it would be fun to use Transport drones to deal with the logistics of so many intermediate products. Fortunately, you already provide a mechanism for changing the transport drone fuel, since Petroleum Gas doesn't actually exist in Bob's. It made sense to me to make it Fuel Oil (the equivalent of light oil).

However, the other issue I ran into is that the drones are made using `engine-unit` but that is also not part of the default Angel's and Bob's run. Angel's does introduce motors which are mostly for the same purpose, with multiple tiers (to cover base engines and electric engines, etc). For example, Automobiles and Tanks need Motor-2 to build.

I do see as part of Angel's industries existing code to replace "engine-unit" with "motor-2"
```
function replace_blocks_list(ing_list) --specifically build to be used for replace_con_mats function
...
    if ing_list[n].name == "engine-unit" then
      ing_list[n].name = "motor-2"
    end
```

My guess is that it doesn't work for Transport drones because they are being generated dynamically (probably because of the dynamic nature of the drones and the recipes how they transport items). Or possibly the Angel's Industries rewrite of ingredients is triggering before transport drones is loaded?

This is what I tried, I'm not sure if it is the right place: `data\entities\transport_drone\transport_drone.lua`:
```
engine_type = "engine-unit"
if mods["angelsindustries"] then
	engine_type = "motor-2"
end

local recipe =
{
  type = "recipe",
  name = name,
  localised_name = {name},
  --category = "transport",
  enabled = false,
  ingredients =
  {
    {engine_type, 1},
    {"steel-plate", 5},
    {"iron-gear-wheel", 5},
  },
  energy_required = 2,
  result = name
}
```

This did do what I wanted, but I don't know if this is a change you would be interested in making, if it should exist in some other way?

**Comment by TimVroom** [comment]
For the manual change of the fluid, i would suggest "gas-methane" as a replacement in e.g settings-updates as a default value if possible. However "liquid-fuel-oil" is also a valid option.

In this case the mayor issue is that its done in data-final-updates.lua.
When its done in the data or data-update stage a lot of the issues in compatibility with angels should be solved. (Not really sure about the data-update stage though).
Not an easy fix to do, but it might require an compatibility mod if klonan doesn't want to include the mod specific changes.

This request was also done on https://github.com/Arch666Angel/mods/issues/218

**Comment by Klonan** [comment]
I am not interested in solving this, mods changing all the recipes in this way is just a painful way of operating
